#!/bin/bash

QEMU=${QEMU:-$HOME/CE/bin/qemu-system-i386}
CEHDPATH=${CEHDPATH:-$HOME/.CE/hd.img}

DEBUG=
if [ "$1" == -g ]; then
	DEBUG="-s -S"
	shift
fi
	
trap 'stty sane' exit

output="-serial stdio"
if [ "$AUTOCORR" == 1 ]; then
	output=-nographic
fi


"$QEMU" $DEBUG		      \
	-kernel build/sistema \
	-hda .swap	      \
	-hdc "$CEHDPATH"      \
	$output 	      \
	-no-reboot 	      |
util/show_log.pl
	
