#!/bin/bash

QEMU=${QEMU:-qemu}

DEBUG=
if [ "$1" == -g ]; then
	DEBUG="-s -S"
	shift
fi
	
trap 'stty sane' exit


"$QEMU" -kernel build/sistema \
	-append -sPM0 	      \
	-hda .swap	      \
	-nographic 	      \
	-no-reboot 	      \
	$DEBUG
