#!/bin/bash

[ -n "$QEMU" ] || {
	QEMU=qemu-system-x86_64
	CEQEMU=$HOME/CE/bin/qemu-system-x86_64
	[ -x "$CEQEMU" ] && QEMU=$CEQEMU
}
CEHDPATH=${CEHDPATH:-$HOME/CE/share/hd.img}

DEBUG=
if [ "$1" == -g ]; then
	DEBUG="-s"
	shift
fi
	
trap 'stty sane' exit

output="-serial stdio"
if [ "$AUTOCORR" == 1 ]; then
	output=-nographic
fi

hdc=
if [ -f "$CDEPATH" ]; then
	hdc="-hdc \"$CDEPATH\""
fi


"$QEMU" $DEBUG 		    		\
	-kernel build/boot 		\
	-initrd build/sistema		\
	${DEBUG:+-append $DEBUG}	\
	-drive file=.swap,cache=unsafe  \
	$hdc                  		\
	$output 	      		\
	-no-reboot 	      		|
util/show_log.pl
