MAKE=make
SWAPSIZE=9000

BUILDDIR=$(BASEDIR)/build

CXXFLAGS=-fleading-underscore -fno-exceptions -fno-rtti

all: sistema io utente util swap

sistema:
	$(MAKE) -C sistema

io:
	$(MAKE) -C io

utente: util
	$(MAKE) -C utente

util:
	$(MAKE) -C util

swap: util utente
	$(BUILDDIR)/createimg $(SWAPSIZE) utente/utente
	

clean:
	$(MAKE) -C sistema clean
	$(MAKE) -C io      clean
	$(MAKE) -C utente  clean
	$(MAKE) -C util    clean
	rm -f $(BUILDDIR)/*

export BASEDIR BUILDDIR CXXFLAGS MAKE

